name: Build

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

env:
  CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          path: my-app/

      - name: Set Node.js Version
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change directory
        run: cd my-app/

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
